In [1]:
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as scio

In [2]:
input_layer_size = 400 #20*20
num_labels = 10

In [3]:
data = scio.loadmat('digit.mat')
X = data['X']
T = data['T']
[d,m,c] = T.shape
print(T.shape)
X.shape

(256, 200, 10)


(256, 500, 10)

In [4]:
S = np.zeros((256,256))
mu = np.zeros((256,c))
for i in range(0,c):
    mu[:,i] = np.mean(X[:,:,i],1)
    S+=np.cov(X[:,:,i])/c           #S的维度（256，256）
h = np.dot(np.linalg.inv(S),mu)#256*256

In [5]:
p = np.zeros((10,200,10))
for k in range(0,c):
    p[:,:,k]=np.dot(h.T,T[:,:,k])-np.tile(sum(np.multiply(mu,h)).reshape(10,1),(1,m))/2
    
pmax = p.

In [13]:
(sum(np.multiply(mu,h))).reshape(10,1)

array([[14650.78811057],
       [14497.60815899],
       [14564.08425477],
       [14618.45163045],
       [14532.94585854],
       [14596.79837146],
       [14631.49081298],
       [14549.92753369],
       [14625.78610853],
       [14554.00011276]])

In [22]:
[index,col,spe] = p.shape
print([index,col,spe])

[10, 200, 10]


In [ ]:
for s in range(spe):
    for i in range(index):
        

In [24]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
k = 0
mmax = A[0]
def mmax(array)
for i in range(len(array)):
    if array[i]>mmax:
        mmax = array[i]
        k=i
print(mmax,k)

9 9


In [27]:
P = p.argmax(axis=0)

In [28]:
P

array([[0, 1, 2, ..., 7, 8, 9],
       [0, 1, 2, ..., 7, 8, 9],
       [0, 1, 2, ..., 7, 8, 9],
       ...,
       [0, 7, 2, ..., 7, 8, 9],
       [0, 1, 2, ..., 3, 8, 9],
       [0, 1, 2, ..., 7, 8, 9]], dtype=int64)

In [29]:
p.shape

(10, 200, 10)