# 距离（判断样本的相似度）
- 闵科夫斯基距离
- 曼哈顿距离
- 欧拉距离
- 极大距离

In [ ]:
import numpy
from scipy.spatial.distance import pdist
X=np.vstack([x,y])
pdist(X, metric='euclidean', *args, **kwargs)

In [ ]:
Y = pdist(X, 'euclidean')

Y = pdist(X, 'minkowski', p=2.)

Y = pdist(X, 'cityblock')

Y = pdist(X, 'seuclidean', V=None)

Y = pdist(X, 'sqeuclidean')

Y = pdist(X, 'cosine')

Y = pdist(X, 'correlation')

Y = pdist(X, 'hamming')

Y = pdist(X, 'jaccard')

Y = pdist(X, 'chebyshev')

Y = pdist(X, 'canberra')

Y = pdist(X, 'braycurtis')

Y = pdist(X, 'mahalanobis', VI=None)

Y = pdist(X, 'yule')

Y = pdist(X, 'matching')

Y = pdist(X, 'dice')

Y = pdist(X, 'kulsinski')

Y = pdist(X, 'rogerstanimoto')

Y = pdist(X, 'russellrao')

Y = pdist(X, 'sokalmichener')

Y = pdist(X, 'sokalsneath')

Y = pdist(X, 'wminkowski', p=2, w=w)

# 余弦相似度

欧式距离：绝对距离  
余弦相似度：方向差异

# 缺失值处理
- 删除法：删除样本或删除特征  
- 均值填补：连续数据用平均值填补，离散数据用众数填补
- 随机填补
- 基于模型的填补：将缺失特征y当作预测目标
- 哑变量：对于离散型的
- EM算法填补

## 1.sklearn方法

In [ ]:
SimpleImputer(missing_values=nan,       # 缺失值的占位符
              trategy='mean',           # 列平均值mean,中位数median，众数most_frequent，常量constant
              fill_value=None,          # 值
              verbose=0,                # 控制详细度
              copy=True,                # 是否重新复制一份
              add_indicator=False)

In [37]:
import numpy as np
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')   # 类

imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])               # 实例化

print(imp_mean.fit_transform([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]]))

X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]

print(imp_mean.transform(X))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   5.   9. ]]
[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


In [ ]:
fit(X[, y])              # 找到imputer

fit_transform(X[, y])    # 自己填充

transform(X)             # 用找到的imputer，填充其他的

## 2.pandas方法

In [ ]:
import pandas as pd 
# pd.isna( 对象 )    # 返回bool类型对象，该对象和源对象一样
# pd.notna( 对象 )

# 对象.isna()
# 对象.notna()


# 对象.fillna(0)
# 对象.fillna(method='pad')    向前pad / ffill    向后bfill / backfill

# 对象.dropna()                删除轴标签缺少数据   指定参数axis=0

# 对象.replace(取代值, 缺失值

# 离群值检测
- 统计方法：在上下a分位点之外的值是异常值
- 近邻的方法：点周围的密度

In [ ]:
LocalOutlierFactor(n_neighbors=20,      #领域数
                   algorithm='auto',    #{'auto'，'ball_tree'，'kd_tree'，'brute'}，可选
                   leaf_size=30,        # Leaf size 用于上面的BallTree or KDTree
                   metric='minkowski',   #用于距离计算的度量
                   p=2,                  #闵可夫距离下，p=1，Manhattan；p=2，euclidean_distance
                   metric_params=None,  #度量功能的其他关键字参数。
                   contamination='auto', #异常值比例
                   novelty=False,        #LocalOutlierFactor仅用于异常值检测（novelty = False）
                   n_jobs=None)          #并行个数


"""
metric的取值（第一个标题）
来自scikit-learn：['cityblock'，'cosine'，'euclidean'，'l1'，'l2'，'manhattan']

来自scipy.spatial.distance：['braycurtis'，'canberra'，'chebyshev'，'correlation'，'dice，'hamming'，
'jaccard'，'kulsinski'，'mahalanobis'，'minkowski'，'rogerstanimoto '，
'russellrao'，'seuclidean'，'sokalmichener'，'sokalsneath'，'sqeuclidean'，'yule']

"""

In [38]:
from sklearn.neighbors import LocalOutlierFactor

X = [[-1.1], [0.2], [101.1], [0.3]]

clf = LocalOutlierFactor(n_neighbors=2)    # 类

print(clf.fit_predict(X))

print(clf.negative_outlier_factor_)

[ 1  1 -1  1]
[ -0.98214286  -1.03703704 -73.36970899  -0.98214286]


In [ ]:
negative_outlier_factor_    # 属性。训练样本的LOF。越高，越正常。(=-1)inliner

n_neighbors_                # 领域数

fit(X[, y])                 # 使用X作为训练数据拟合模型

fit_predict(X[, y])         # 将模型拟合到训练集X并返回标签

kneighbors([X, n_neighbors, …])  # 找到一个点的K领域

kneighbors_graph([X, n_neighbors, mode])  # 计算加权图

# 数据转换的方法

# 特征编码
- 数字编码（缺点：次序问题）
- One-Hot编码（缺点：维数增多，引入了特征相关性）
- 哑变量编码（将K个变成K-1个二元特征）

## 数字编码

In [6]:
from sklearn.preprocessing import LabelEncoder        # 类

le = LabelEncoder()                                    # 实例化

print(le.fit(["M", "M", "F", "F","unknow"]))           # 拟合数字编码

print(le.fit_transform(["M", "M", "F", "F","unknow"])) # 拟合数字编码并返回编码

print(le.classes_)                                     # 输出拟合的标签

print(le.transform(["M","unknow","F","M"]))            # 用实例化后的le转化其他的编码

print(le.inverse_transform([1,1,1,1,2,0]))             # 将标签翻译成数字编码

LabelEncoder()
[1 1 0 0 2]
['F' 'M' 'unknow']
[1 2 0 1]
['M' 'M' 'M' 'M' 'unknow' 'F']


0：F  
1：M  
2: unknow

In [ ]:
classes_             #属性，输出拟合的所有标签

fit(y)               # 拟合标签编码器

fit_transform(y)     # 拟合标签编码器并返回编码的标签

inverse_transform(y) # 将标签转换回原始编码。

transform(y)         # 将标签转换为规范化编码。

## One-Hot编码

### 1.sklearn方法

In [ ]:
"""
输入：整数或字符串之类的数组
输出：稀疏矩阵或密集数组
"""
OneHotEncoder(categories='auto',               # 输入自动
              drop=None,                      # 删除某些列None，'first'，drop[i]
              sparse=True,                    # True，返回稀疏矩阵，否则返回数组
              dtype=<class 'numpy.float64'>,  # 输出类型
              handle_unknown='error')          # 引发错误或忽略(ignore)，默认引发

In [19]:
from sklearn.preprocessing import OneHotEncoder   # 类

enc = OneHotEncoder(handle_unknown='ignore')       # 实例化

X = [['Male', 1], ['Female', 3], ['Female', 2]]    

print(enc.fit(X))                                  # 拟合One-Hot编码

print(enc.fit_transform(X).toarray())              # 拟合One-Hot编码并返回One-Hot编码

print(enc.categories_)                             # 在拟合过程中确定的每个特征的类别

print(enc.transform([['Female', 1], ['Male', 4]]).toarray())

print(enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]]))

print(enc.get_feature_names(['gender', 'group']))

drop_enc = OneHotEncoder(drop='first').fit(X)      # 删除每个功能中的第一个类别

print(drop_enc)

print(drop_enc.categories_)

print(drop_enc.fit_transform(X).toarray())

print(drop_enc.transform([['Female', 1], ['Male', 2]]).toarray())

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)
[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0.]]
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
[[1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
[['Male' 1]
 [None 2]]
['gender_Female' 'gender_Male' 'group_1' 'group_2' 'group_3']
OneHotEncoder(categories='auto', drop='first', dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[0. 0. 0.]
 [1. 1. 0.]]


In [ ]:
        F  M  1  2  3
(M,1)   0  1  1  0  0
(F,3)   1  0  0  0  1
(F,2)   1  0  0  1  0

------------------------
        M  2  3
(M,1)   1  0  0
(F,3)   0  0  1
(F,2)   0  1  0

In [ ]:
categories_            # 属性，在拟合过程中确定的每个特征的类别

fit(X[, y])            # 使OneHotEncoder适应X

fit_transform(X[, y])  # 使OneHotEncoder适应X，然后变换X

get_feature_names(input_features=None) # 返回输出要素的名称

inverse_transform(X)   # 将数据转换回原始表示形式

transform(X)            # 使用OneHotEncoder转换X

### 2.pandas方法

In [ ]:
pandas.get_dummies(data, 
                   prefix=None,              # 用于追加DataFrame列名称的字符串。
                   prefix_sep='_',           # 如果附加前缀，则使用分隔符_
                   dummy_na=False,          # 增加一列显示这行是否空值，如果没有空值那么为0，如果这行为空值，那么为1
                   columns=None,            # 要编码的DataFrame中的列名，如果columns为None，则将转换所有对象或类别为 dtype 的列
                   sparse=False,            #  True稀疏，False numpy数组
                   drop_first=False,        #是否减少一列
                   dtype=None)              #类型

In [26]:
import pandas as pd 

data = pd.Series(['a','b','c','a'])

print(pd.get_dummies(data))

print(pd.get_dummies(data, dummy_na=True))

print(pd.get_dummies(data, prefix='前缀'))

print(pd.get_dummies(data, drop_first=True))

print(pd.get_dummies(data, dtype=float))

   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0
   a  b  c  NaN
0  1  0  0    0
1  0  1  0    0
2  0  0  1    0
3  1  0  0    0
   前缀_a  前缀_b  前缀_c
0     1     0     0
1     0     1     0
2     0     0     1
3     1     0     0
   b  c
0  0  0
1  1  0
2  0  1
3  0  0
     a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0


# 数据标准化
- Z-score标准化
- Min-Maxi标准化
- 小数定标标准化
- Logistic标准化

In [ ]:
sklearn.preprocessing.StandardScaler
sklearn.preprocessing.MinMaxScaler
sklearn.preprocessing.RobustScaler #使用对异常值具有鲁棒性的统计

## 1.Z-score标准化

In [ ]:
StandardScaler(copy=True,     #是否复制
               with_mean=True, #数据是否居中
               with_std=True) # 将数据缩放到单位方差

In [40]:
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1]]

scaler = StandardScaler()

print(scaler.fit(data))

print(scaler.mean_)

print(scaler.var_)

print(scaler.transform(data))

print(scaler.transform([[2, 2]]))   # (2-0.5)/0.5

StandardScaler(copy=True, with_mean=True, with_std=True)
[0.5 0.5]
[0.25 0.25]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]


In [ ]:
mean_                        # 属性。训练集中每个特征的平均值

var_                         # 属性。训练集中每个要素的方差

fit(X[, y])                  # 计算均值和std以用于以后的缩放

fit_transform(X[, y])

inverse_transform(X[, copy]) # 将数据按比例缩小到原始表示形式

partial_fit(X[, y])          # 计算X上的均值和标准差，以便以后标准化

transform(X[, y, copy])      # 通过居中和缩放执行标准化

## 2.Min-Maxi标准化

In [ ]:
MinMaxScaler(feature_range=(0, 1),   #(最小，最大)
             copy=True)

In [41]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

scaler = MinMaxScaler()

print(scaler.fit(data))

print(scaler.data_max_)

print(scaler.transform(data))

print(scaler.transform([[2, 2]]))

MinMaxScaler(copy=True, feature_range=(0, 1))
[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[[1.5 0. ]]


In [ ]:
data_min_            # 属性。查看最小值
data_max_            # 属性。查看最大值
data_range_          # 属性。最大值-最小值

方法同上

Min-Maxi标准化变种

In [ ]:
RobustScaler(with_centering=True,           #是否数据居中
             with_scaling=True,             #是否缩放到分位数范围
             quantile_range=(25.0, 75.0),   #分位数范围
             copy=True)

In [ ]:
from sklearn.preprocessing import RobustScaler

# 特征离散化

连续变成区间(离散)

- 二值离散化
- 等距离散化
- 等频离散化
- 聚类离散化
-----------
- 信息增益离散化
- 卡方离散化

## 二值离散化

In [ ]:
Binarizer(threshold=0.0,     # 低于或等于替换为0，高于替换为1
          copy=True)         # 是否复制

In [28]:
from sklearn.preprocessing import Binarizer
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
transformer = Binarizer().fit(X)

print(transformer)

print(transformer.transform(X))

Binarizer(copy=True, threshold=0.0)
[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
fit(X[, y])

fit_transform(X[, y])

transform(X[, copy])

## 等距离散化

In [ ]:
pandas.cut(x,                                 # 必须是一维的数组
           bins,                              # 离散化标准：int，标量序列或pd.IntervalIndex
           right: bool = True,               # 是否右闭区间
           labels=None,                      # 指定标签，长度和bin一样
           retbins: bool = False,            # 是否返回bins
           precision: int = 3,               # 存储和显示bins标签的精度
           include_lowest: bool = False,     # 第一个时间间隔是否应包含在内
           duplicates: str = 'raise')        # 如果bin边缘不是唯一的，则 raise ValueError或drop non-uniques

In [32]:
import numpy as np
import pandas as pd

print(pd.cut(np.array([1, 7, 5, 4, 6, 3]), 3),'\n')

print(pd.cut(np.array([1, 7, 5, 4, 6, 3]), 3, retbins=True),'\n')

print(pd.cut(np.array([1, 7, 5, 4, 6, 3]),3, labels=["bad", "medium", "good"]))

[(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]] 

([(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]], array([0.994, 3.   , 5.   , 7.   ])) 

[bad, good, medium, medium, good, bad]
Categories (3, object): [bad < medium < good]


## 等频离散化

In [ ]:
pandas.qcut(x,                            # 必须是一维的数组或Series对象
            q,                            # 分位数  4为四分位数
            labels=None, 
            retbins: bool = False, 
            precision: int = 3, 
            duplicates: str = 'raise')

In [34]:
import pandas as pd 

pd.qcut(range(5), 3, labels=["good", "medium", "bad"])

[good, good, medium, bad, bad]
Categories (3, object): [good < medium < bad]

## 聚类离散化